---
#Default Connectivity variables 

ansible_user: "roger"
ansible_ssh_pass: "cisco"
ansible_network_os: "ios"
ansible_connection: "network_cli"

# Classic Provider Details for use with aireos

legacy_credentials:
  host: "{{ ansible_host }}"
  username: "roger"
  password: "Password$"






  



