---
## Playbook to get system time and append it to backup files

- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}}
     file:
      path: ~/network-programmability/backups/{{hostvars.localhost.DTG}}
      state: directory
  run_once: true

- hosts: NXOS
  gather_facts: false

  tasks:
   - name: Backup NEXUS Devices
     cli_command:
       commands:
         - show run | be version
     register: config

   - name: Save output to ~/projects/network-programmability/backups/
     copy:
       content: "{{config.stdout[0]}}"
       dest: "~/network-programmability/backups/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-config.txt"





